google/neper

check_all_options.c
common.c
common.h
control_plane.c
define_all_flags.c
lib.h
socket.c
thread.c

* xweng@: Add support for enabling FREEBIND socket option.
* xweng@: When --host is specified on server side, bind to the given host address.
* dzinn@: Allow specifying the source port used for the data connections
* wsommerfeld@: Add locks around accesses to rusage_start and time_start within run_main_thread()
Signed-off-by: Venkatesh Srinivas <venkateshs@chromium.org>

Update neper to catch up with Google internal changes through 2019-08-20

---

lib.h
rr.c
tcp_crr.c

For tcp_crr server, a new flow is created for each short-lived
connection.  If we collect stats, flow's neper_stat will be added
to worker thread's neper_stats, and won't be freed until the worker
thread ends.  It will use a lot of memory (~1GB/sec) and cause test
failures.
For other four workloads including tcp_crr client, the number of
flows is specified by command line flag, so the memory useage is
stable.
Fixes: 253d3b405 ("neper: collect stats in *rr servers (#22)")

neper: don't collect latency stats in tcp_crr server (#22)

---

common.c

SO_ZEROCOPY is not defined in EL7 kernel headers, hence the compliation will fail on CentOS7/RHEL7.
Tested: compile on CentOS7

Manually define SO_ZEROCOPY if needed

---

define_all_flags.c
lib.h
socket.c

Neper clients set socket option SO_LINGER with linger timeout of 0.
This triggers an abortive close, where the socket sends an RST instead
of a FIN when it closes its end of the connection.
This avoids entering TIME_WAIT state, which may exhaust available
sockets with many test connections.
But optionally skip this step, to test the entire normal TCP
lifecycle including TIME_WAIT.
Tested:
ss -nt state time-wait
shows no connections with standard tcp_stream
shows all connections with tcp_stream --time-wait,
if that option is passed on the client,
then the TIME_WAIT sockets appear on the server
(which is apparently the active close side)

neper: optionally enter TIME_WAIT state

---

cpuinfo.c
logging.c
rusage.c
thread.c

This includes:
- Switching from `HZ` to `sysconf(_SC_CLK_TCK)` [1]
- Switching to `pthread_setaffinity_np` after the thread has been created [2]
- Removing the GNU specifc [3] fcloseall() as the following exit() will also flush
- Adding support for parsing `/proc/cpuinfo`
[1]: https://man7.org/linux/man-pages/man5/proc.5.html
[2]: https://www.openwall.com/lists/musl/2015/05/08/24
[3]: https://man7.org/linux/man-pages/man3/fcloseall.3.html
Signed-off-by: Michael Hope <mlhx@google.com>

neper: add support for Linux on RISC-V with musl

---

check_all_options.c
common.c
common.h

In unprivileged network namaespaces - that is network namespaces owned by
a non-init user namespace - the sysctls in /proc/sys/net/core are not
accessible.  This caused neper tools to fail on startup since the
procfile_int() call in check_options_common() would hit a fatal error if
it couldn't open /proc/sys/net/core/somaxconn.
Allow neper to run in such a namespace by only making the check if
/proc/sys/net/core/somaxconn is openable.  Since this was the only caller
of procfile_int(), remove it and just open-code the new version within
check_options_common().
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>

Allow neper to run in an unprivileged network namespace

---

README.md
common.c
common.h
define_all_flags.c
lib.h
socket.c

usage: ./tcp_rr -t 100
Tested:
ran tcp_rr across 2 machines
```
~$ dmesg
[76807.565177] TCP: TCP_TX_DELAY enabled
```

add flag to enable TCP_TX_DELAY sockopt

---

check_all_options.c
define_all_flags.c
socket.c

Linux 5.10 extended SO_MAX_PACING_RATE to 64 bit, allowing more
than 4GB/s per socket.
Adjust variable sizes to pass the full 64 bits to the kernel.
Earlier kernels will silently truncate to 32 bits.
Tested: run experiment with argument bigger than 32 bits.
(It takes a fast link to verify that a single flow can achieve
the requested rate).

Pacing 64bit

---

control_plane.c
control_plane.h
define_all_flags.c
lib.h
rr.c
stream.c
thread.c
thread.h

This option on the client side periodically prints io statistics (tx and rx operations, bytes and Mbps) so it is possible to monitor throughput variations in real time.
netperf has a similar option.
Tested: run with --iostat-ms 1000

neper: new option --iostat-ms N prints io statistics periodically

---

define_all_flags.c
flow.c
lib.h
psp_stream_main.c
stream.c
tcp_stream_main.c

In bidirectional mode, acks are piggybacked behind data and this creates unwanted dependencies between forward and reverse flows.
To solve the problem, IN BIDIRECTIONAL STREAM MODE ONLY we use one tcp socket per direction (the user-specified number of flows is doubled after option parsing), used as follows:
- client and server always read from all sockets
- client sends only on half of the sockets (those witheven f_id). This is done by disabling EPOLLOUT on alternate sockets.
- server starts sending on all sockets, but will stop sending and disable EPOLLOUT on sockets on which data is received. This is done in stream_handler()
The above allows to have half of the sockets in tx, and half in rx, without control plane modifications.
Tested: manual test with -rw and different '-m' values on …

neper: use one socket per flow in bidirectional stream mode

---

psp_lib.c
socket.c

fix error when -Wincompatible-pointer-types is included

explicit cast from sockaddr_{in,in6} to sockaddr

---

Dockerfile
Makefile
README_tcpdevmem.md
run_neper_container.sh
tcpdevmem.c
tcpdevmem.h
tcpdevmem_cuda.cu
tcpdevmem_udma.c

**Assumes that kernel hdr files are in usr/ folder in your Neper working directory.**
Changes from git pulling tcpd branch within the container, to copying the source files from current Neper dir into the container, then building with those files.
Tested: docker build for CUDA & ran tcp_stream CUDA across 2 VMs

build CUDA-neper image on workstation

---

Dockerfile
Makefile

This allows to use neper in environments like kubernetes
```
make image
docker build --tag neper:2ae2467 .
Sending build context to Docker daemon    812kB
...
Step 16/16 : ENTRYPOINT [ "/busybox/sleep", "infinity" ]
---> Using cache
---> f891b1afe800
Successfully built f891b1afe800
Successfully tagged neper:2ae2467
```

use neper in a container image

---

tcpdevmem_cuda.cu

fixes malformed vec when recvmsg buffer_size is too large

increase msg_control buffer size

---

check_all_options.c
define_all_flags.c
lib.h
thread.c

This option on the client side will delay the client from creating any threads (and thus flows) after the control connection has been established. It can be useful if multiple neper server-client pairs are created over the same link, and the link gets too congested from earlier pairs for the later ones to successfully establish the control connection. The option can also be used to set up simulated packet dropping rules between making the control connection and sending traffic.
Tested:
./tcp_stream -c -H 127.0.0.1 --wait-start 5 --logtostderr
Verified that the client waited for 5 seconds before starting to send traffic.

neper: new option --wait-start to delay starting client data flows

---

multi_neper.py
tcpdevmem.c
tcpdevmem.h
thread.c

Tested: build Docker image and run tcp_stream in CUDA TCPDEVMEM mode across 2 VMs

Tcpdevmem driver reset in binary instead of multi_neper.py

---

README_tcpdevmem.md
run_neper_container.sh

example:
```
IMAGE="gcr.io/a3-tcpd-staging-hostpool/${USER}/neper"
./run_neper_container.sh -i "${IMAGE}" bash
./run_neper_container.sh -i $IMAGE bash
```

use stable/dev Docker images

---

percentiles.c

The current code takes a list of comma separated 'double' values representing the latency percentile data points that the user is interested in. The user might repeat a particular percentile value. To prevent printing the same percentile data point twice, the code (percentile.c) sorts the list of percentiles requested by the user, in the order of their percentile values, i.e. higher percentiles will be sorted at the end.
After sorting and removing the duplicates, the code incorrectly sets the number of the percentiles to one less than the actual count. This results in the code not printing the last percentile in the provided list of percentile arguments.
For example,
option_used_in_cmd>  -p 50.0,95.0,99.0, results in the following
stdout_results>    percentiles=50,95
This patch fixes the …

[Fix] Prevent skipping the last latency percentile list argument

---

README.md
snaps.c
snaps.h
stats.h
stream.c

include some previously omitted header files (lint complaints)
Stream clients only take 1 snapshot, but doesn't properly return timespec start_time.
However, tries to take snapshots too many times, reducing throughput on udp_stream significantly.
Reduce it so only 2 snapshots are needed.
author: lixiaoyan@

minor clean-up (imports, snapshots)

---

stats.c
thread.c

For tcp_rr/tcp_stream (and other binaries), --test-length flag can be negative to mean transaction numbers. (See: define_all_flags.c)
However, not all code paths correctly handles this negative number, which leads to a negative size number passed to alloc.
This PR also fixed a nit - replacing "sizeof(*a_null_pointer)" with "sizeof(the type that the pointer points to)".  (Dereferencing a null pointer is always sth to avoid)
Tested:
build the binary and manually run it on workstation and devrez machines with --test-length=-600000

Fixed segfault when test_length is negative.

---

socket.c

Setting TCP_TX_DELAY right after socket creation makes SYN/SYN-ACK packets also
get delayed. This introduces extra amount of time to establish the connections
when -F is high. This is not ideal and does not reflect the reality of pacing.
This change moves the TCP_TX_DELAY setting to after 3WHS is finished and the
socket is in established state.
Author: Wei Wang

Move TCP_TX_DELAY setsockopt after 3WHS

---

check_all_options.c
control_plane.c
countdown_cond.h
define_all_flags.c
logging.c
parse.c
parse.h
psp_lib.c
snaps.c
socket.c

You can still pass naked numbers e.g. "999" that will be interpreted as nanoseconds, but above suffixes are also now supported.
Counting out zeroes is a huge nuisance, this makes neper a little more usable.

add ns/us/ms/s suffixes to --delay

---

.gitignore

Log files are created by default and don't need to be tracked.

add .log files to .gitignore

---

README.md

add some guidelines to use the neper images in kubernetes

docs: explain how to use neper in Kubernetes

---

check_all_options.c
common.c
common.h
define_all_flags.c
flags.h
flow.c
flow.h
lib.h
psp_stream_main.c
rr.c
socket.c
stream.c
tcp_stream_main.c
thread.c
thread.h
udp_stream_main.c

While we have some support for TCP TX zerocopy via MSG_ZEROCOPY, there is no support for TCP_ZEROCOPY_RECEIVE. This patchset adds that support.

TCP RX zerocopy

---

define_all_flags.c

Reverts google/neper#88
"-R " shortname is already being used in tcp_rr for response_size. 
```
-R, --reuseaddr                  Use SO_REUSEADDR on sockets (default 0)
-R, --response-size              Number of bytes in a response from server to client (default 1)
```

Revert "add --reuseaddr to rr binaries"

---

common.c
common.h
define_all_flags.c
lib.h
socket.c
tcp_stream_main.c

Add no_delay and no_cork options to help allow tcp_stream to send small packets
no_delay -- disable Nagle's algorithm on data sockets
no_cork -- If set, do not use MSG_MORE flag when sending with tcp_stream
MSG_MORE logic in tcp_stream was not upstreamed yet so I added the line to set the flag if no_cork is not used.
When used together, tcp_stream won't coalesce small writes into larger packets.

Add no_delay and no_cork flags to help tcp_stream send small packets
